image: ${CI_REGISTRY}/build-images/python-gems:latest

stages:
  - build
  - mirror_to_github
  - publish_to_nuget

build:
  stage: build
  script:
    - python3 /app/build_gems.py
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^20\d\d\/v\d+\s*$/

mirror_to_github:
  stage: mirror_to_github
  #when: manual
  script:
    - python3 /app/mirror_to_github.py
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^20\d\d\/v\d+$/

publish_to_nuget:
  stage: publish_to_nuget
  #when: manual
  script:
    - python3 /app/publish_to_nuget.py  
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^20\d\d\/v\d+$/
