image: ${CI_REGISTRY}/build-images/python-gems:latest

stages:
  - test
  - build
  - mirror_to_github
  - publish_to_nuget
  - prepare_release
  - create_release

build:
  stage: build
  script:
    - python3 /app/build_gems.py
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^20\d\d\/v\d+\s*$/

build_test:
  stage: build
  script:
    - python3 /app/build_gems_test.py
  only:
    - /^feature\/.*$

mirror_to_github:
  stage: mirror_to_github
  #when: manual
  script:
    - python3 /app/mirror_to_github.py
  only:
    - main
  variables:
    - $CI_COMMIT_TAG =~ /^20\d\d\/v\d+$/

publish_to_nuget:
  stage: publish_to_nuget
  #when: manual
  script:
    - python3 /app/publish_to_nuget.py
  only:
    - main
  variables:
    - $CI_COMMIT_TAG =~ /^20\d\d\/v\d+$/

test:
  stage: test
  image: ${CI_REGISTRY}/build-images/core/sdk:8.0
  services:
    - docker:20.10.8-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  script:
    - dotnet test --framework net8.0 -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutput=../results/
  coverage: '/Total\s*\|\s*(\d+\.?\d+)/'
  artifacts:
    reports:
      cobertura: ../results/coverage.net8.0.cobertura.xml
  tags:
    - dind

prepare_release:
  stage: prepare_release
  image: alpine:latest
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - apk add curl jq
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
  only:
    - main
  artifacts:
    paths:
    - release_notes.md

create_release:
  stage: create_release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_release
      artifacts: true
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release"
  only:
    - main
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'Container Image $CI_COMMIT_TAG'
          url: "https://$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
